const $=id=>document.getElementById(id);
let employees=JSON.parse(localStorage.employees||"[]"), attendance=JSON.parse(localStorage.attendance||"[]");
function login(){if($("uid").value && $("pwd").value){$("login").classList.add("hidden");$("app").classList.remove("hidden");refresh()}else alert("Enter User ID and Password");}
function logout(){$("app").classList.add("hidden");$("login").classList.remove("hidden")}
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");refresh()}
function refresh(){ $("empCount").textContent=employees.length; $("attCount").textContent=attendance.length;
$("empTable").innerHTML=employees.map((e,i)=>`<tr><td>${e.name}</td><td>${e.designation}</td><td>${e.join||""}</td><td>₹${Number(e.salary||0).toLocaleString("en-IN")}</td><td><button onclick="delEmp(${i})">Delete</button></td></tr>`).join("");
let opts=employees.map((e,i)=>`<option value="${i}">${e.name} — ${e.designation}</option>`).join("");$("attEmp").innerHTML=opts;$("docEmp").innerHTML=opts;
$("attTable").innerHTML=attendance.map(a=>`<tr><td>${a.date}</td><td>${a.name}</td><td>${a.status}</td></tr>`).join("");
}
function addEmployee(ev){ev.preventDefault();employees.push({name:$("name").value,designation:$("designation").value,department:$("department").value,join:$("join").value,salary:$("salary").value,food:$("food").value});localStorage.employees=JSON.stringify(employees);ev.target.reset();refresh()}
function delEmp(i){if(confirm("Delete employee?")){employees.splice(i,1);localStorage.employees=JSON.stringify(employees);refresh()}}
function addAttendance(){let i=$("attEmp").value;if(!employees[i])return;attendance.push({date:$("attDate").value,name:employees[i].name,status:$("attStatus").value});localStorage.attendance=JSON.stringify(attendance);refresh()}
function fillEmployee(){let e=employees[$("docEmp").value];if(!e)return;$("basic").value=e.salary||0;$("food2").value=e.food||0;$("fromDate").value=e.join||""}
function toggleSalary(){let s=$("docType").value==="salary";$("salaryFields").classList.toggle("hidden",!s);$("letterFields").classList.toggle("hidden",s)}
function money(n){return Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}
function generateDoc(){let e=employees[$("docEmp").value];if(!e)return alert("Add/select employee first");let type=$("docType").value,date=$("docDate").value||new Date().toISOString().slice(0,10);
if(type==="salary"){let basic=+$("basic").value,hra=+$("hra").value,site=+$("site").value,medical=+$("medical").value,special=+$("special").value,food=+$("food2").value,pf=+$("pf").value,pt=+$("pt").value,loan=+$("loan").value,total=basic+hra+site+medical+special+food,ded=pf+pt+loan,net=total-ded;
$("preview").innerHTML=`<div class="doc"><h1>NAVRUP INDIA</h1><div class="center">House No: 53, Tokobari Satra A.T. Road, Guwahati, Assam</div><h2 class="center">PAYSLIP</h2><table><tr><td>Date of Joining</td><td>${e.join||""}</td><td>Employee Name</td><td>${e.name}</td></tr><tr><td>Pay Period</td><td>${$("period").value}</td><td>Designation</td><td>${e.designation}</td></tr><tr><td>Worked Days</td><td>${$("worked").value}</td><td>Department</td><td>${e.department||""}</td></tr></table><table><tr><th>Earnings</th><th>Amount</th><th>Deductions</th><th>Amount</th></tr><tr><td>Basic</td><td>₹${money(basic)}</td><td>Provident Fund</td><td>₹${money(pf)}</td></tr><tr><td>House Rent Allowance</td><td>₹${money(hra)}</td><td>Professional Tax</td><td>₹${money(pt)}</td></tr><tr><td>Site Allowance</td><td>₹${money(site)}</td><td>Loan</td><td>₹${money(loan)}</td></tr><tr><td>Medical Allowance</td><td>₹${money(medical)}</td><td></td><td></td></tr><tr><td>Special Allowance</td><td>₹${money(special)}</td><td></td><td></td></tr><tr><td>Food Allowance</td><td>₹${money(food)}</td><td></td><td></td></tr><tr><th>Total Earnings</th><th>₹${money(total)}</th><th>Total Deductions</th><th>₹${money(ded)}</th></tr><tr><td></td><td></td><th>Net Pay</th><th>₹${money(net)}</th></tr></table><p><b>Amount in Words:</b> ${net.toLocaleString("en-IN")} Rupees Only</p><div class="sign"><span>Employer Signature</span><span>Employee Signature</span></div></div>`;
}else{let title=type==="service"?"TO WHOM IT MAY CONCERN":"Relieving Letter",project=$("project").value||"the assigned project",from=$("fromDate").value||e.join,to=$("toDate").value||date;
$("preview").innerHTML=`<div class="doc"><h1>NAVRUP INDIA</h1><div class="center">H.NO 53, GROUND FLOOR, A.T ROAD TOKOBARI SATRA, GUWAHATI-01, ASSAM<br>GSTN: 18AANFN5145J1ZU</div><p><b>Date:</b> ${date}</p><h2 class="center">${title}</h2><p>Dear ${e.name},</p>${type==="service"?`<p>This is to certify that Mr. ${e.name} was employed with NAVRUP INDIA as a ${e.designation} from ${from} to ${to}.</p><p>During his tenure, he successfully performed his responsibilities for ${project}. He demonstrated professional commitment to safety, quality, leadership and timely project delivery.</p><p>He has successfully completed his responsibilities and handed over his charge. We appreciate his valuable contribution to NAVRUP INDIA and wish him continued success.</p>`:`<p>This is to formally confirm the acceptance of your resignation and relieve you from your duties at NAVRUP INDIA, effective ${to}.</p><p>You joined the company on ${from} and have successfully completed your responsibilities, exit formalities and handover.</p><p>We sincerely appreciate your dedication and valuable contribution to our projects. We wish you continued success in your future career.</p>`}<p>Sincerely,</p><div class="sign"><span>NAVRUP INDIA</span><span>Authorized Signatory</span></div></div>`}
window.print()}
toggleSalary();